# Generated by Django 4.0.5 on 2022-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('marcaProducto', models.CharField(max_length=20)),
                ('stockProducto', models.CharField(max_length=20)),
                ('precioProducto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('idPromociones', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePromociones', models.CharField(max_length=50)),
                ('marcaPromociones', models.CharField(max_length=20)),
                ('stockPromociones', models.CharField(max_length=20)),
                ('precioPromociones', models.CharField(max_length=20)),
                ('descuentoPromociones', models.CharField(max_length=20)),
                ('fechainiPromociones', models.CharField(max_length=10)),
                ('fechaterPromociones', models.CharField(max_length=10)),
                ('preciofinPromociones', models.CharField(max_length=20)),
            ],
        ),
    ]
