# Generated by Django 4.0.5 on 2022-07-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='idPromociones',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
