# Generated by Django 4.0.5 on 2022-07-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='idPromociones',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
